### PR TITLE
Add generated Google TTS UI voices

### PR DESCRIPTION
**Pull request by panmarco83**
all english speaking, but if the transcripts could be translated to other languages, I could probably create other language versions too.

### CODE REVIEW

**Comment by panmarco83** [comment]
Is it too large ? Or are you worried about possible legal issues regarding the Google TTS files ?
I can strip out the GTTS files and put them somewhere else (not git) if anyone wants them.

**Comment by jbaicoianu** [comment]
It is a bit on the large side - I hadn't considered if there were any legal issues, I'm honestly not sure what the terms of use are for saved Google TTS recordings.

I wonder if it makes sense to introduce the concept of asset packs, so you'd have one basic set of sound effects installed by default, but with the ability to easily download additional ones (new languages, custom sound effect packs, etc)?  Then we could host these somewhere else - either as separate git repositories, or wherever else makes the most sense.

What do you think?

**Comment by panmarco83** [comment]
True, okay.
I have removed the tts stuff now, will it work to just push now or do I need to make a new pull request ?

**Comment by jbaicoianu** [comment]
Should be able to just push, the pull request will track the latest commits to your branch

**Comment by panmarco83** [comment]
Done, is this better ?

**Comment by panmarco83** [comment]
The female-original is the original voice from waaaay back

**Comment by panmarco83** [comment]
Hey, is this mergable now ?

**Comment by panmarco83** [comment]
it's the ooold voice, the slightly newer voice and the british male voice

**Comment by jbaicoianu** [comment]
Thanks for cleaning this up

**Pull request merged**
